export const character_data = [
    {
        name: "amber",
        fullname: "Amber",
        element: "pyro",
        rarity: 4,
        weapon: "bow",
        ascension: [
            "agnidus_agate",
            "everflame_seed",
            "small_lamp_grass",
            "firm_arrowhead",
        ],
        talent: [
            "freedom",
            "firm_arrowhead",
        ],
    },
    {
        name: "barbara",
        fullname: "Barbara",
        element: "hydro",
        rarity: 4,
        weapon: "catalyst",
        ascension: [
            "varunada_lazurite",
            "cleansing_heart",
            "philanemo_mushroom",
            "divining_scroll",
        ],
        talent: [
            "freedom",
            "divining_scroll",
        ],
    },
    {
        name: "beidou",
        fullname: "Beidou",
        element: "electro",
        rarity: 4,
        weapon: "claymore",
        ascension: [
            "vajrada_amethyst",
            "lightning_prism",
            "noctilucous_jade",
            "treasure_hoarder_insignia",
        ],
        talent: [
            "gold",
            "treasure_hoarder_insignia",
        ],
    },
    {
        name: "bennett",
        fullname: "Bennett",
        element: "pyro",
        rarity: 4,
        weapon: "sword",
        ascension: [
            "agnidus_agate",
            "everflame_seed",
            "windwheel_aster",
            "treasure_hoarder_insignia",
        ],
        talent: [
            "resistance",
            "treasure_hoarder_insignia",
        ],
    },
    {
        name: "chongyun",
        fullname: "Chongyun",
        element: "cryo",
        rarity: 4,
        weapon: "claymore",
        ascension: [
            "shivada_jade",
            "hoarfrost_core",
            "cor_lapis",
            "damaged_mask",
        ],
        talent: [
            "diligence",
            "damaged_mask",
        ],
    },
    {
        name: "diluc",
        fullname: "Diluc",
        element: "pyro",
        rarity: 5,
        weapon: "claymore",
        ascension: [
            "agnidus_agate",
            "everflame_seed",
            "small_lamp_grass",
            "recruit_insignia",
        ],
        talent: [
            "resistance",
            "recruit_insignia",
        ],
    },
    {
        name: "fischl",
        fullname: "Fischl",
        element: "electro",
        rarity: 4,
        weapon: "bow",
        ascension: [
            "vajrada_amethyst",
            "lightning_prism",
            "small_lamp_grass",
            "firm_arrowhead",
        ],
        talent: [
            "ballad",
            "firm_arrowhead",
        ],
    },
    {
        name: "jean",
        fullname: "Jean",
        element: "anemo",
        rarity: 5,
        weapon: "sword",
        ascension: [
            "vayuda_turquoise",
            "hurricane_seed",
            "dandelion_seed",
            "damaged_mask",
        ],
        talent: [
            "resistance",
            "damaged_mask",
        ],
    },
    {
        name: "kaeya",
        fullname: "Kaeya",
        element: "cryo",
        rarity: 4,
        weapon: "sword",
        ascension: [
            "shivada_jade",
            "hoarfrost_core",
            "calla_lily",
            "treasure_hoarder_insignia",
        ],
        talent: [
            "ballad",
            "treasure_hoarder_insignia",
        ],
    },
    {
        name: "keqing",
        fullname: "Keqing",
        element: "electro",
        rarity: 5,
        weapon: "sword",
        ascension: [
            "vajrada_amethyst",
            "lightning_prism",
            "cor_lapis",
            "whopperflower_nectar",
        ],
        talent: [
            "prosperity",
            "whopperflower_nectar",
        ],
    },
    {
        name: "klee",
        fullname: "Klee",
        element: "pyro",
        rarity: 5,
        weapon: "catalyst",
        ascension: [
            "agnidus_agate",
            "everflame_seed",
            "philanemo_mushroom",
            "divining_scroll",
        ],
        talent: [
            "freedom",
            "divining_scroll",
        ],
    },
    {
        name: "lisa",
        fullname: "Lisa",
        element: "electro",
        rarity: 4,
        weapon: "catalyst",
        ascension: [
            "vajrada_amethyst",
            "lightning_prism",
            "valberry",
            "slime_condensate",
        ],
        talent: [
            "ballad",
            "slime_condensate",
        ],
    },
    {
        name: "mona",
        fullname: "Mona",
        element: "hydro",
        rarity: 5,
        weapon: "catalyst",
        ascension: [
            "varunada_lazurite",
            "cleansing_heart",
            "philanemo_mushroom",
            "whopperflower_nectar",
        ],
        talent: [
            "resistance",
            "whopperflower_nectar",
        ],
    },
    {
        name: "ningguang",
        fullname: "Ningguang",
        element: "geo",
        rarity: 4,
        weapon: "catalyst",
        ascension: [
            "prithiva_topaz",
            "basalt_pillar",
            "glaze_lily",
            "recruit_insignia",
        ],
        talent: [
            "prosperity",
            "recruit_insignia",
        ],
    },
    {
        name: "noelle",
        fullname: "Noelle",
        element: "geo",
        rarity: 4,
        weapon: "claymore",
        ascension: [
            "prithiva_topaz",
            "basalt_pillar",
            "valberry",
            "damaged_mask",
        ],
        talent: [
            "resistance",
            "damaged_mask",
        ],
    },
    {
        name: "qiqi",
        fullname: "Qiqi",
        element: "cryo",
        rarity: 5,
        weapon: "sword",
        ascension: [
            "shivada_jade",
            "hoarfrost_core",
            "violetgrass",
            "divining_scroll",
        ],
        talent: [
            "prosperity",
            "divining_scroll",
        ],
    },
    {
        name: "razor",
        fullname: "Razor",
        element: "electro",
        rarity: 4,
        weapon: "claymore",
        ascension: [
            "vajrada_amethyst",
            "lightning_prism",
            "wolfhook",
            "damaged_mask",
        ],
        talent: [
            "resistance",
            "damaged_mask",
        ],
    },
    {
        name: "sucrose",
        fullname: "Sucrose",
        element: "anemo",
        rarity: 4,
        weapon: "catalyst",
        ascension: [
            "vayuda_turquoise",
            "hurricane_seed",
            "windwheel_aster",
            "whopperflower_nectar",
        ],
        talent: [
            "freedom",
            "whopperflower_nectar",
        ],
    },
    {
        name: "traveler_anemo",
        fullname: "Traveler (Anemo)",
        element: "anemo",
        rarity: 5,
        weapon: "sword",
        ascension: [
            "brilliant_diamond",
            "windwheel_aster",
            "damaged_mask",
        ],
        talent: [
        ],
    },
    {
        name: "traveler_geo",
        fullname: "Traveler (Geo)",
        element: "geo",
        rarity: 5,
        weapon: "sword",
        ascension: [
            "brilliant_diamond",
            "windwheel_aster",
            "damaged_mask",
        ],
        talent: [
        ],
    },
    {
        name: "venti",
        fullname: "Venti",
        element: "anemo",
        rarity: 5,
        weapon: "bow",
        ascension: [
            "vayuda_turquoise",
            "hurricane_seed",
            "cecilia",
            "slime_condensate",
        ],
        talent: [
            "ballad",
            "slime_condensate",
        ],
    },
    {
        name: "xiangling",
        fullname: "Xiangling",
        element: "pyro",
        rarity: 4,
        weapon: "polearm",
        ascension: [
            "agnidus_agate",
            "everflame_seed",
            "jueyun_chili",
            "slime_condensate",
        ],
        talent: [
            "diligence",
            "slime_condensate",
        ],
    },
    {
        name: "xiao",
        fullname: "Xiao",
        element: "anemo",
        rarity: 5,
        weapon: "polearm",
        ascension: [
            "vayuda_turquoise",
            "hurricane_seed",
            "qingxin",
            "firm_arrowhead",
        ],
        talent: [
            "prosperity",
            "firm_arrowhead",
        ],
    },
    {
        name: "xingqiu",
        fullname: "Xingqiu",
        element: "hydro",
        rarity: 4,
        weapon: "sword",
        ascension: [
            "varunada_lazurite",
            "cleansing_heart",
            "silk_flower",
            "damaged_mask",
        ],
        talent: [
            "gold",
            "damaged_mask",
        ],
    },
];
export const character_map = character_data.reduce((acc, cur) => ({...acc, [cur.name]: cur}), {});